//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace main
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Dob { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<double> Donate { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public Nullable<int> Tel { get; set; }
        public string Stand { get; set; }
        public string Class { get; set; }
    }
}
